//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstacionamentoEntities : DbContext
    {
        public EstacionamentoEntities()
            : base("name=EstacionamentoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<lEstacionamento> lEstacionamento { get; set; }
        public virtual DbSet<TipoVeiculo> TipoVeiculo { get; set; }
        public virtual DbSet<VagaVeiculo> VagaVeiculo { get; set; }
        public virtual DbSet<Veiculo> Veiculo { get; set; }
    }
}
