//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.VagaVeiculo = new HashSet<VagaVeiculo>();
        }
    
        public int IdFuncionario { get; set; }
        public double Salario { get; set; }
        public string Nome { get; set; }
        public long CPF { get; set; }
        public int IdEstacionamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VagaVeiculo> VagaVeiculo { get; set; }
        public virtual lEstacionamento lEstacionamento { get; set; }
    }
}
